// Generates generated/typescript/protocol.d.ts from schemas/ and enums/.
//
//   node codegen/typescript/generate.mjs [--out <dir>]
//
// json-schema-to-typescript produces the building blocks: payloads, enums,
// the shared envelope fields (Common) and the relay block. The message types
// themselves are composed here, not generated, because the generator writes
// the inbound envelope as `relay?: never` — which still lets code read
// `msg.relay`. Composed from Common, an inbound message has no relay at all,
// so reading it is a compile error. See docs/adr/0011-two-envelope-types.md.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname, resolve, relative, isAbsolute } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const outArg = process.argv.indexOf('--out');
const OUT = outArg > 0 ? resolve(process.argv[outArg + 1]) : join(ROOT, 'generated', 'typescript');

const BANNER = `// Generated by codegen/typescript/generate.mjs from schemas/ and enums/.
// Do not edit. \`npm run codegen\` rewrites this file, and codegen-verify fails
// on any hand edit. Change the schema instead.
`;

const readJson = (rel) => JSON.parse(readFileSync(join(ROOT, rel), 'utf8'));

// Same naming the generator applies to a schema title: "session-claim v1" -> "SessionClaimV1".
const typeName = (title) =>
  title.split(/[^A-Za-z0-9]+/).filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join('');

// A $ref with a sibling description makes the generator emit a duplicate,
// renamed type (Endpoint1, MessageType1). Annotations next to a $ref are
// dropped for generation only; the schema files are untouched.
function stripRefSiblings(node) {
  if (Array.isArray(node)) return node.map(stripRefSiblings);
  if (node === null || typeof node !== 'object') return node;
  const out = {};
  for (const [k, v] of Object.entries(node)) {
    if ('$ref' in node && (k === 'description' || k.startsWith('x-'))) continue;
    out[k] = stripRefSiblings(v);
  }
  return out;
}

const messageTypes = readJson('enums/message-type.json').enum;
const payloads = messageTypes.map((type) => {
  const matches = ['control', 'pairing', 'task', 'command', 'approval', 'replay']
    .map((dir) => `schemas/${dir}/${type}.v1.json`)
    .filter((rel) => {
      try {
        return readFileSync(join(ROOT, rel), 'utf8').length > 0;
      } catch {
        return false;
      }
    });
  if (matches.length !== 1) throw new Error(`message type "${type}": ${matches.length} payload schemas, expected 1`);
  const file = matches[0];
  return { type, file, name: typeName(readJson(file).title) };
});

const root = {
  title: 'ProtocolSchema',
  type: 'object',
  additionalProperties: false,
  properties: {
    Common: { $ref: 'schemas/envelope.v1.json#/$defs/common' },
    RelayBlock: { $ref: 'schemas/envelope.v1.json#/$defs/relayBlock' },
    MessageType: { $ref: 'enums/message-type.json' },
    Endpoint: { $ref: 'enums/endpoint.json' },
    CloseReason: { $ref: 'enums/close-reason.json' },
    ...Object.fromEntries(payloads.map((p) => [p.name, { $ref: p.file }])),
  },
};

const localOnly = {
  order: 1,
  canRead: true,
  read(file) {
    const path = fileURLToPath(file.url.startsWith('file:') ? file.url : `file:///${file.url}`);
    const rel = relative(ROOT, path);
    if (rel.startsWith('..') || isAbsolute(rel)) {
      throw new Error(`refusing to read outside the repo: ${path}`);
    }
    return JSON.stringify(stripRefSiblings(JSON.parse(readFileSync(path, 'utf8'))));
  },
};

let ts = await compile(root, 'ProtocolSchema', {
  additionalProperties: false,
  bannerComment: '',
  format: true,
  cwd: ROOT,
  $refOptions: { resolve: { file: localOnly, http: false } },
});

// The bundle root only exists to reach every schema in one pass.
const rootBlock = /\nexport interface ProtocolSchema \{\n[\s\S]*?\n\}\n/;
if (!rootBlock.test(ts)) throw new Error('generator output changed shape: ProtocolSchema block not found');
ts = ts.replace(rootBlock, '\n');

for (const name of ['Common', 'RelayBlock', 'MessageType', 'Endpoint', 'CloseReason', ...payloads.map((p) => p.name)]) {
  if (!new RegExp(`^export (type|interface) ${name}\\b`, 'm').test(ts)) {
    throw new Error(`generator output has no type ${name}`);
  }
}
const payloadNames = new Set(payloads.map((p) => p.name));
const renamed = [...ts.matchAll(/^export (?:type|interface) ([A-Za-z0-9]+)/gm)]
  .map((m) => m[1])
  .filter((name) => /\d$/.test(name) && !payloadNames.has(name));
if (renamed.length) throw new Error(`generator emitted duplicated, renamed types: ${renamed.join(', ')}`);

const composition = `
// ---------------------------------------------------------------------------
// Messages. Composed by codegen/typescript/generate.mjs, not by the generator.
// ---------------------------------------------------------------------------

/** The payload type for each message type. */
export interface PayloadFor {
${payloads.map((p) => `  ${JSON.stringify(p.type)}: ${p.name};`).join('\n')}
}

/** The envelope fields every message carries, apart from \`type\` and \`payload\`. */
export type EnvelopeFields = Omit<Common, "type" | "payload">;

/**
 * A message as a desktop or phone sends it to the relay. It has no \`relay\`
 * field, so code holding one cannot read or write a relay block. Narrow on
 * \`type\` to get the payload's type.
 */
export type InboundMessage<T extends MessageType = MessageType> = {
  [K in T]: EnvelopeFields & { type: K; payload: PayloadFor[K] };
}[T];

/** A message as the relay delivers it: an inbound message plus the relay block it stamped. */
export type OutboundMessage<T extends MessageType = MessageType> = {
  [K in T]: EnvelopeFields & { type: K; payload: PayloadFor[K]; relay: RelayBlock };
}[T];
`;

mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, 'protocol.d.ts'), (BANNER + ts.trimEnd() + '\n' + composition).replace(/\r\n/g, '\n'));
console.log(`typescript: ${relative(ROOT, join(OUT, 'protocol.d.ts')) || join(OUT, 'protocol.d.ts')}`);
