"""Generates the Python package in generated/python/ from schemas/ and enums/.

    python codegen/python/generate.py [--out <dir>]

datamodel-code-generator produces the building blocks (payloads, enums, the
shared envelope fields). The message types are composed here: the generator
writes the inbound envelope with an optional `relay: Any`, which would let a
relay block through, so the envelope types are built from the schema's own
field list instead. The checker source in codegen/python/runtime/ and copies of
the schemas are added, giving an installable package.

Run it with the exact toolchain in codegen/python/requirements.txt: generated
output depends on every version there, the formatters most of all.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
PACKAGE = "deskaway_protocol"

HEADER = (
    "# Generated by codegen/python/generate.py from schemas/ and enums/.\n"
    "# Do not edit. `npm run codegen` rewrites this file, and codegen-verify fails\n"
    "# on any hand edit. Change the schema instead."
)
COPY_HEADER = "# Copied by codegen/python/generate.py from codegen/python/runtime/{name}. Edit the source, not this copy.\n"

# How each envelope field's schema maps to a name in types.py.
REF_ALIASES = {
    "#/$defs/uuidV4": "UuidV4",
    "#/$defs/runId": "RunId",
    "#/$defs/utcTimestamp": "UtcTimestamp",
    "../enums/message-type.json": "MessageType",
    "../enums/endpoint.json": "Endpoint",
}


def type_name(title: str) -> str:
    """The generator's naming for a schema title: "session-claim v1" -> "SessionClaimV1"."""
    return "".join(w[0].upper() + w[1:] for w in re.split(r"[^A-Za-z0-9]+", title) if w)


def read_json(rel: str) -> Any:
    return json.loads((ROOT / rel).read_text("utf-8"))


def non_empty_json(folder: Path) -> list[Path]:
    return sorted(p for p in folder.rglob("*.json") if p.stat().st_size > 0)


def payload_schemas() -> list[tuple[str, str, str]]:
    """(message type, schema path, generated class name) for every message type."""
    out = []
    for message_type in read_json("enums/message-type.json")["enum"]:
        matches = [p for p in (ROOT / "schemas").glob(f"*/{message_type}.v1.json") if p.stat().st_size > 0]
        if len(matches) != 1:
            raise SystemExit(f'message type "{message_type}": {len(matches)} payload schemas, expected 1')
        rel = matches[0].relative_to(ROOT).as_posix()
        out.append((message_type, rel, type_name(read_json(rel)["title"])))
    return out


def generate_types(work: Path, payloads: list[tuple[str, str, str]]) -> str:
    for folder in ("schemas", "enums"):
        shutil.copytree(ROOT / folder, work / folder)
    bundle = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "ProtocolSchema",
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "Common": {"$ref": "schemas/envelope.v1.json#/$defs/common"},
            "RelayBlock": {"$ref": "schemas/envelope.v1.json#/$defs/relayBlock"},
            "CloseReason": {"$ref": "enums/close-reason.json"},
            **{name: {"$ref": rel} for _, rel, name in payloads},
        },
    }
    (work / "protocol.json").write_text(json.dumps(bundle, indent=2), "utf-8")
    out = work / "types.py"
    subprocess.run(
        [
            sys.executable, "-m", "datamodel_code_generator",
            "--input", str(work / "protocol.json"),
            "--input-file-type", "jsonschema",
            "--output", str(out),
            "--output-model-type", "typing.TypedDict",
            "--target-python-version", "3.11",
            "--enum-field-as-literal", "all",
            "--use-title-as-name",
            "--use-closed-typed-dict",
            "--disable-timestamp",
            "--formatters", "black", "isort",
            "--custom-file-header", HEADER,
            "--no-allow-remote-refs",
        ],
        check=True,
        cwd=work,
    )
    text = out.read_text("utf-8")
    # The bundle root only exists to reach every schema in one pass.
    root_block = re.compile(r"\n\n\nclass ProtocolSchema\(TypedDict, closed=True\):\n(?:    .*\n|\n)*?(?=\n\n|\Z)")
    if not root_block.search(text):
        raise SystemExit("generator output changed shape: ProtocolSchema block not found")
    return root_block.sub("\n", text).strip() + "\n"


def compose_messages(types_py: str, payloads: list[tuple[str, str, str]]) -> str:
    def require(name: str) -> str:
        if not re.search(rf"^(class {name}\b|{name}(: TypeAlias)? = )", types_py, re.M):
            raise SystemExit(f"types.py has no {name}; the generator's naming changed")
        return name

    common = read_json("schemas/envelope.v1.json")["$defs"]["common"]
    required = set(common["required"])

    def field_type(name: str, schema: dict[str, Any], payload_class: str, message_type: str) -> str:
        if name == "type":
            return f'Literal["{message_type}"]'
        if name == "payload":
            return payload_class
        if "const" in schema:
            return f"Literal[{json.dumps(schema['const'])}]"
        if "$ref" in schema and schema["$ref"] in REF_ALIASES:
            return require(REF_ALIASES[schema["$ref"]])
        raise SystemExit(f"envelope field {name!r} has a shape the Python composer does not know: {schema}")

    lines = [
        HEADER,
        "",
        '"""Message types: the envelope fields with each type\'s payload.',
        "",
        "Composed by codegen/python/generate.py, not by the generator. An inbound",
        "message has no relay field at all; an outbound one requires it.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Literal, NotRequired, TypeAlias",
        "",
        "from typing_extensions import TypedDict",
        "",
        "from .types import (",
        *sorted({f"    {n}," for n in ["Endpoint", "RelayBlock", "RunId", "UtcTimestamp", "UuidV4", *[p[2] for p in payloads]]}),
        ")",
        "",
    ]
    inbound_names, outbound_names = [], []
    for message_type, _, payload_class in payloads:
        require(payload_class)
        base = type_name(message_type)
        fields = []
        for name, schema in common["properties"].items():
            t = field_type(name, schema, payload_class, message_type)
            fields.append(f'        "{name}": {t if name in required else f"NotRequired[{t}]"},')
        for suffix, extra, names in (("Inbound", [], inbound_names), ("Outbound", ['        "relay": RelayBlock,'], outbound_names)):
            cls = f"{base}{suffix}"
            names.append(cls)
            lines += ["", f"{cls} = TypedDict(", f'    "{cls}",', "    {", *fields, *extra, "    },", "    closed=True,", ")", ""]
    lines += [
        "",
        "InboundMessage: TypeAlias = " + " | ".join(inbound_names),
        '"""A message as a device sends it to the relay. There is no relay field."""',
        "",
        "OutboundMessage: TypeAlias = " + " | ".join(outbound_names),
        '"""A message as the relay delivers it, with the relay block it stamped."""',
        "",
        "Payload: TypeAlias = " + " | ".join(p[2] for p in payloads),
        "",
    ]
    return "\n".join(lines)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.replace("\r\n", "\n"), "utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=ROOT / "generated" / "python")
    out: Path = parser.parse_args().out.resolve()

    payloads = payload_schemas()
    with tempfile.TemporaryDirectory() as tmp:
        types_py = generate_types(Path(tmp), payloads)
    messages_py = compose_messages(types_py, payloads)

    if out.exists():
        shutil.rmtree(out)
    pkg = out / "src" / PACKAGE
    write(out / "pyproject.toml", (HERE / "templates" / "pyproject.toml").read_text("utf-8"))
    write(pkg / "types.py", types_py)
    write(pkg / "messages.py", messages_py)
    write(pkg / "py.typed", "")
    for name in ("__init__.py", "check.py"):
        write(pkg / name, COPY_HEADER.format(name=name) + (HERE / "runtime" / name).read_text("utf-8"))
    for folder in ("schemas", "enums"):
        for src in non_empty_json(ROOT / folder):
            write(pkg / "_contract" / src.relative_to(ROOT), src.read_text("utf-8"))
    print(f"python: {out.relative_to(ROOT) if out.is_relative_to(ROOT) else out}")


if __name__ == "__main__":
    main()
